name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: build image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
    
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.1'
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Load secrets and store to app.env
        run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --outpu text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

      - name: Build, tag, and push docker image to Amazon ECR
        env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: simplebank
            IMAGE_TAG: ${{ github.sha }}
        run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
            docker push -a $REGISTRY/$REPOSITORY
    
      - name: Update kube config
        run: aws eks update-kubeconfig --name simple-bank --region ca-central-1
      
      - name: Deploy image to Amazon EKS
        run: |
            kubectl apply -f eks/aws-auth.yaml
            kubectl apply -f eks/deployment.yaml
            kubectl apply -f eks/service.yaml
            kubectl apply -f eks/issuer.yaml
            kubectl apply -f eks/ingress.yaml
